### ISSUE TITLE
Organiser credits: Whitespace not trimmed after submission

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#435] opened 2021-01-16 14:21 UTC
When copying orga credits e.g. from a party website, the names may be surrounded by whitespace. The JavaScript parser correctly trims it and suggests the correct scener. But as soon as you hit "Add organiser", you get to a page that tells you that the name was not found, so you manually have to remove the surrounding whitespace in order to submit the name. Since the JaveScript implementation already does it, the serverside implementation should probably do the same.

**Comment by glennlunder** [comment] 2021-01-16 15:24
I think I've seen that exact behaviour on normal credits adding on productions as well, so that may help pinpoint where the problem is.

**Comment by gasman** [comment] 2021-01-16 23:47
Thanks for reporting! Fixed in a6c71baf5aa7771bc5a9e250cfc78d9d5855e5c4.

**Closed by gasman** 2021-01-16 23:47 UTC
