### ISSUE TITLE
Marking of Awards - nominations and wins

### ISSUE THREAD

**Issue by glennlunder** [demozoo/demozoo#189] opened 2016-03-10 14:59 UTC
Scene.org awards and Meteoriks nominations and wins should be properly marked with some sort of "label", much like it is on Pouët.

Nominated productions serve a nice double duty as viewing tips and as such have more than one set of values. Some nice pixeled award statues could be arranged.

**Comment by emoon** [comment] 2016-03-11 10:49
+1 for this :)

**Comment by gasman** [comment] 2016-05-23 19:54
Duplicate of #66

**Closed by gasman** 2016-05-23 19:54 UTC
