### ISSUE TITLE
Set info files/board ads as NSFW content

### ISSUE THREAD

**Issue by m100bit** [demozoo/demozoo#506] opened 2021-12-28 19:50 UTC
Everything in the title.
[Example](https://demozoo.org/bbs/2287/text_ad/4945/) if we really need this function (NSFW warning, yes).

**Comment by sagamusix** [comment] 2022-01-05 12:22
This is essentially a duplicate of #36 (though at the time of creating that, BBS / NFO files didn't exist yet, so they should also be taken into account there)

**Comment by sagamusix** [comment] 2022-01-05 12:23
@glennlunder I'd suggest to close this in favor of the already existing issue.

**Comment by glennlunder** [comment] 2022-01-05 13:04
Agreed.

**Closed by glennlunder** 2022-01-05 13:04 UTC
