### ISSUE TITLE
Search bug: key word queries blocked?

### ISSUE THREAD

**Issue by bengarrett** [demozoo/demozoo#626] opened 2024-11-07 21:09 UTC
Search does not return any results for "not", "and" and "is" despite the New Productions, By form queries returning valid results. 

I was initially searching for the group "not!" and not finding anything despite: https://demozoo.org/groups/131373/

**Comment by gasman** [comment] 2024-11-07 21:16
Thanks for the report! I think this can be considered a duplicate of #381.

**Closed by gasman** 2024-11-07 21:16 UTC

**Comment by bengarrett** [comment] 2024-11-07 21:45
Thanks. Would there be no way to implement the search used by the New Productions auto completion in the main Search, even as a toggle or advanced query?

![Screenshot From 2024-11-08 07-54-02](https://github.com/user-attachments/assets/69be1f7c-ee7b-4a6b-95ea-4b94d8e92329)
![Screenshot From 2024-11-08 07-54-42](https://github.com/user-attachments/assets/4f866a34-ab9f-48e8-abad-db0ecc467128)
