### ISSUE TITLE
Missing size for input fields in link editor popups

### ISSUE THREAD

**Issue by sagamusix** [demozoo/demozoo#257] opened 2016-10-10 15:58 UTC
Simlar to #236, the size of input fields in the "Downloads" and "External Links" popup boxes does not seem to be specified leading to ugly line breaks on systems with large paddings on input elements. See attached screenshot.

![screenshot_2016-10-10_17-55-48](https://cloud.githubusercontent.com/assets/875883/19242382/23de6edc-8f13-11e6-9bfe-bd82aa5d57a6.png)

**Comment by nswaldman** [comment] 2016-10-10 19:27
Unable to reproduce this and apparently there's some customisation at fault on your end too?

Still. Even if that's the case, there are some layout improvements we can do to make the thing more bullet-proof for UI discrepancies like this.

**Comment by sagamusix** [comment] 2016-10-10 19:33
I don't think it's any customisation I have done myself, but I cannot tell for sure which GTK theme is being used, because - as mentioned on Slack - Xubuntu is still mostly GTK2 (including the theme editor), but Firefox uses GTK3. So far I have not investigated how I could change the GTK3 theme to something more sensible that doesn't add tons of padding to all my input fields. :)

**Comment by nswaldman** [comment] 2016-10-10 19:38
Well, we're pocketing you for layout testing in the foreseeable future regardless, you are a magnet for form discrepancies ;)

**Comment by glennlunder** [comment] 2016-10-11 04:36
FWIW, I can reproduce in Firefox on Solus OS's (which rocks btw!) custom desktop Budgie, which is fully GTK3. Chrome is fine under the same conditions.

**Comment by sagamusix** [comment] 2016-10-11 10:52
So anything using the default GTK3 theme (?) might be usable for testing.

**Comment by gasman** [comment] 2018-03-07 01:56
Fixed in #340

**Closed by gasman** 2018-03-07 01:56 UTC
Labels: css
